# Декларативная загрузка определений (vhosts, users, policies, queues)
load_definitions = /etc/rabbitmq/definitions.json

# Кластеризация через classic config (статический список нод)
cluster_formation.peer_discovery_backend = classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbit1
cluster_formation.classic_config.nodes.2 = rabbit@rabbit2
cluster_formation.classic_config.nodes.3 = rabbit@rabbit3

cluster_partition_handling = pause_minority
prometheus.return_per_object_metrics = true
