// Code generated by command: go run gen.go -out dotavo_amd64.s -stubs dotavo_stub_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func dotAvoAVX2(a *float64, b *float64, n int) float64
// Requires: AVX, FMA3, SSE2
TEXT ·dotAvoAVX2(SB), NOSPLIT, $0-32
	MOVQ   a+0(FP), AX
	MOVQ   b+8(FP), CX
	MOVQ   n+16(FP), DX
	VXORPD Y0, Y0, Y0
	MOVQ   DX, BX
	SHRQ   $0x02, BX

blockloop:
	CMPQ        BX, $0x00
	JE          reduce
	VMOVUPD     (AX), Y1
	VMOVUPD     (CX), Y2
	VFMADD231PD Y2, Y1, Y0
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	DECQ        BX
	JMP         blockloop

reduce:
	VEXTRACTF128 $0x01, Y0, X1
	VADDPD       X1, X0, X0
	VHADDPD      X0, X0, X0
	ANDQ         $0x03, DX

tailloop:
	CMPQ        DX, $0x00
	JE          done
	VMOVSD      (AX), X1
	VMOVSD      (CX), X2
	VFMADD231SD X2, X1, X0
	ADDQ        $0x08, AX
	ADDQ        $0x08, CX
	DECQ        DX
	JMP         tailloop

done:
	MOVSD X0, ret+24(FP)
	VZEROUPPER
	RET
