// Code generated by command: go run gen.go -out dotavo_amd64.s -stubs dotavo_stub_amd64.go. DO NOT EDIT.

package avo

// dotAvoAVX2 — сгенерированное avo скалярное произведение (AVX2+FMA).
func dotAvoAVX2(a *float64, b *float64, n int) float64
