CREATE EXTENSION IF NOT EXISTS pgstattuple;

-- Три таблицы, идентичные во всём, КРОМЕ типа первичного ключа.
-- Одинаковая полезная нагрузка (payload) — чтобы различие в размере и
-- локальности объяснялось ТОЛЬКО ключом, а не данными.
CREATE TABLE k_bigint (
  id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payload text NOT NULL,
  created timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE k_uuid4 (
  id     uuid PRIMARY KEY,          -- заполняется UUIDv4 из loader
  payload text NOT NULL,
  created timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE k_uuid7 (
  id     uuid PRIMARY KEY,          -- заполняется uuidv7() / из loader
  payload text NOT NULL,
  created timestamptz NOT NULL DEFAULT now()
);

-- Вторичный индекс для артефакта 2 добавляется там же, отдельным скриптом,
-- чтобы мерить его размер изолированно.
